BEGIN;
CREATE SCHEMA IF NOT EXISTS larz;
REVOKE ALL ON SCHEMA larz FROM PUBLIC, anon, authenticated;
CREATE TABLE IF NOT EXISTS larz.members(user_id uuid PRIMARY KEY REFERENCES auth.users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS larz.products(id uuid PRIMARY KEY, name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200), sku text NOT NULL UNIQUE CHECK(length(sku) BETWEEN 1 AND 80), price_myr numeric(14,2) NOT NULL CHECK(price_myr>=0), price_usd numeric(14,2) NOT NULL CHECK(price_usd>=0), stock integer NOT NULL DEFAULT 0 CHECK(stock>=0), low_stock integer NOT NULL DEFAULT 5 CHECK(low_stock>=0), active boolean NOT NULL DEFAULT true, revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS larz.documents(id uuid PRIMARY KEY, number text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','confirmed','cancelled','legacy')), data jsonb NOT NULL, revision integer NOT NULL DEFAULT 1, source_invoice uuid REFERENCES larz.documents(id), created_by uuid REFERENCES auth.users(id), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS larz.stock_movements(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, product_id uuid NOT NULL REFERENCES larz.products(id), document_id uuid REFERENCES larz.documents(id), delta integer NOT NULL, reason text NOT NULL, actor uuid REFERENCES auth.users(id), operation_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(operation_id,product_id));
CREATE TABLE IF NOT EXISTS larz.operations(id uuid PRIMARY KEY, actor uuid NOT NULL, action text NOT NULL, payload_hash text NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS larz.settings(id integer PRIMARY KEY CHECK(id=1), data jsonb NOT NULL, revision integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS larz.counters(prefix text PRIMARY KEY, value integer NOT NULL);
ALTER TABLE larz.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE larz.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE larz.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE larz.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE larz.operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE larz.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE larz.counters ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA larz FROM PUBLIC,anon,authenticated;
COMMIT;
