require('./lib/config.cjs');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),auth=require('./lib/auth.cjs'),inventory=require('./lib/inventory.cjs');
const secure=!!process.env.VERCEL||process.env.COOKIE_SECURE==='1',attempts=new Map();
const publicFiles={'/login':'login.html','/login.css':'login.css','/assets/larz-logo.png':'assets/larz-logo.png'};
const privateFiles={'/':'index.html','/index.html':'index.html','/src/app.js':'src/app.js','/src/core.js':'src/core.js','/src/style.css':'src/style.css','/src/cloud.js':'src/cloud.js','/src/revenue.js':'src/revenue.js','/src/pdf.js':'src/pdf.js','/assets/vendor/jspdf.umd.min.js':'assets/vendor/jspdf.umd.min.js'};
const csrfCookie=req=>/(?:^|;\s*)larz_csrf=([a-f0-9]{64})(?:;|$)/.exec(req.headers.cookie||'')?.[1];
function send(res,status,message,json=false){res.writeHead(status,{'Content-Type':json?'application/json':'text/plain; charset=utf-8'});res.end(json?JSON.stringify(message):message)}
function redirect(res,to){res.writeHead(303,{Location:to});res.end()}
async function body(req,max){let bytes=0,text='';for await(const chunk of req){bytes+=Buffer.byteLength(chunk);if(bytes>max)throw Object.assign(Error('Request too large.'),{status:413});text+=chunk}return text}
async function handler(req,res){
 res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
 let url;try{if(req.url.length>2048)return send(res,414,'URL too long');url=new URL(req.url,'http://localhost')}catch{return send(res,400,'Invalid URL')}
 try{
 if(url.pathname.startsWith('/api/')){const user=await auth.user(req);if(!user)return send(res,401,{error:'Session expired. Sign in again; your local draft is preserved.'},true);if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,await inventory.state(user),true);if(req.method!=='POST')return send(res,405,{error:'Method not allowed'},true);if(!csrfCookie(req)||req.headers['x-csrf-token']!==csrfCookie(req))return send(res,403,{error:'Reload the page and try again.'},true);if((req.headers['content-type']||'').split(';')[0]!=='application/json')return send(res,415,{error:'Expected JSON'},true);let data;try{data=JSON.parse(await body(req,2000000))}catch(e){if(e.status)throw e;return send(res,400,{error:'Invalid JSON'},true)}return send(res,200,await inventory.mutate(url.pathname.slice(5),data,user),true)}
 if(req.method==='POST'){
  if(!['/login','/logout'].includes(url.pathname))return send(res,404,'Not found');
  if((req.headers['content-type']||'').split(';')[0]!=='application/x-www-form-urlencoded')return send(res,415,'Unsupported content type');
  const data=new URLSearchParams(await body(req,4096)),allowed=url.pathname==='/login'?['username','password','csrf']:['csrf'];
  if([...data.keys()].some(k=>!allowed.includes(k))||allowed.some(k=>data.getAll(k).length!==1))return send(res,400,'Invalid form fields');
  if(!csrfCookie(req)||data.get('csrf')!==csrfCookie(req))return send(res,403,'Your form expired. Refresh the login page.');
  if(url.pathname==='/logout'){await auth.logout(req);res.setHeader('Set-Cookie',`larz_access=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secure?'; Secure':''}`);return redirect(res,'/login')}
  const email=data.get('username').trim().toLowerCase(),password=data.get('password');if(email.length>254||!/^\S+@\S+\.\S+$/.test(email)||!password||password.length>256||/[\x00-\x1f]/.test(password))return send(res,400,'Enter a valid email and password.');
  const ip=String(process.env.VERCEL?req.headers['x-forwarded-for']:req.socket.remoteAddress);for(const [key,v] of attempts)if(v.until<Date.now())attempts.delete(key);if(attempts.size>10000)return send(res,429,'Try again later.');let rate=attempts.get(ip)||{count:0,until:Date.now()+900000};attempts.set(ip,rate);if(++rate.count>10)return send(res,429,'Too many attempts. Try again in 15 minutes.');
  const session=await auth.login(email,password);if(!session)return redirect(res,'/login?error=1');attempts.delete(ip);res.setHeader('Set-Cookie',`larz_access=${session.access_token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.min(session.expires_in||3600,3600)}${secure?'; Secure':''}`);return redirect(res,'/');
 }
 if(!['GET','HEAD'].includes(req.method))return send(res,405,'Method not allowed');
 let file;if(Object.hasOwn(publicFiles,url.pathname))file=publicFiles[url.pathname];else{if(!Object.hasOwn(privateFiles,url.pathname))return send(res,404,'Not found');if(!await auth.user(req))return redirect(res,'/login');file=privateFiles[url.pathname]}
 let data=await fs.promises.readFile(path.join(__dirname,file));if(file==='login.html'||file==='index.html'){const csrf=csrfCookie(req)||crypto.randomBytes(32).toString('hex');res.setHeader('Set-Cookie',`larz_csrf=${csrf}; HttpOnly; SameSite=Strict; Path=/${secure?'; Secure':''}`);data=Buffer.from(data.toString().replace(/(<form\b[^>]*method="post"[^>]*>)/g,`$1<input type="hidden" name="csrf" value="${csrf}">`).replace('</head>',`<meta name="csrf-token" content="${csrf}"></head>`));}if(file==='login.html')data=Buffer.from(data.toString().replace('<!--ERROR-->',url.searchParams.has('error')?'<p class="error" role="alert">Incorrect email or password, or account has no workspace access.</p>':''));res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.png':'image/png'})[path.extname(file)]);res.end(req.method==='HEAD'?undefined:data);
 }catch(e){const status=e.status|| (e.code==='23505'?409:503);const message=e.status?e.message:e.code==='23505'?'That SKU or document number already exists.':'Service unavailable. Try again shortly.';send(res,status,url.pathname.startsWith('/api/')?{error:message}:message,url.pathname.startsWith('/api/'))}
}
const server=http.createServer(handler);if(require.main===module)server.listen(Number(process.env.PORT||4173),'127.0.0.1',()=>console.log('Larz Studio: http://127.0.0.1:'+(process.env.PORT||4173)));module.exports=server;
