const crypto=require('node:crypto'),core=require('../src/core.js'),database=require('./database.cjs');
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
function fail(message,status=400){throw Object.assign(Error(message),{status})}
function string(v,max=200){return typeof v==='string'&&v.trim().length>0&&v.length<=max&&!/[\x00-\x1f]/.test(v)}
function integer(v,max=1e7){return Number.isSafeInteger(v)&&v>=0&&v<=max}
function sameItems(a,b){return a.length===b.length&&a.every((x,i)=>['productId','description','qty','price'].every(k=>x[k]===b[i][k]))}
function document(row){return {...row.data,id:row.id,number:row.number,status:row.status,revision:row.revision,sourceInvoice:row.source_invoice}}
async function state(user){const sql=database();return sql.begin(async tx=>{await tx`set transaction isolation level repeatable read read only`;const products=await tx`select * from larz.products where deleted_at is null order by name`;const docs=await tx`select * from larz.documents where deleted_at is null order by updated_at`;const deleted=await tx`select id from larz.documents where deleted_at is not null`;const settings=await tx`select * from larz.settings where id=1`;const moves=await tx`select m.id,m.delta,m.reason,m.created_at,p.name,d.number from larz.stock_movements m join larz.products p on p.id=m.product_id left join larz.documents d on d.id=m.document_id order by m.id desc limit 100`;return {products:products.map(p=>({...p,price_myr:Number(p.price_myr),price_usd:Number(p.price_usd)})),documents:docs.map(document),deletedDocumentIds:deleted.map(d=>d.id),settings:settings[0]||null,movements:moves,email:user.email}})}
async function mutate(action,input,user){if(!input||typeof input!=='object'||!uuid(input.operationId))fail('Invalid request identifier.');const sql=database(),hash=crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex');return sql.begin(async tx=>{await tx`select pg_advisory_xact_lock(582741921)`;const [existing]=await tx`select * from larz.operations where id=${input.operationId}`;if(existing){if(existing.actor!==user.id||existing.action!==action||existing.payload_hash!==hash)fail('Request identifier already used.',409);return existing.result}let result={ok:true};
if(action==='delete-product'||action==='delete-document'){
 if(!uuid(input.id)||!Number.isInteger(input.revision))fail('Invalid deletion request.');
 if(action==='delete-product'){
 const [p]=await tx`select * from larz.products where id=${input.id} for update`;if(!p||p.deleted_at)fail('Product was already deleted.',409);if(p.revision!==input.revision)fail('Product changed. Refresh before deleting.',409);
 await tx`update larz.products set deleted_at=now(),active=false,revision=revision+1 where id=${p.id}`;
 }else{
 const [d]=await tx`select * from larz.documents where id=${input.id} for update`;if(!d||d.deleted_at)fail('Document was already deleted.',409);if(d.revision!==input.revision)fail('Document changed. Refresh before deleting.',409);
 const [linked]=await tx`select id from larz.documents where source_invoice=${d.id} and deleted_at is null limit 1`;if(linked)fail('Delete linked receipts before deleting this invoice.');
 if(d.status==='confirmed'&&!d.source_invoice){const quantities=new Map();for(const i of d.data.items)quantities.set(i.productId,(quantities.get(i.productId)||0)+i.qty);for(const [id,qty] of [...quantities].sort()){const [p]=await tx`select stock from larz.products where id=${id} for update`;if(!p||p.stock+qty>1e7)fail('Stock cannot be restored.');await tx`update larz.products set stock=stock+${qty},revision=revision+1 where id=${id}`;await tx`insert into larz.stock_movements(product_id,document_id,delta,reason,actor,operation_id) values(${id},${d.id},${qty},'Sale deleted',${user.id},${input.operationId})`;}}
 await tx`update larz.documents set deleted_at=now(),revision=revision+1,updated_at=now() where id=${d.id}`;
 }
}else if(action==='product'){
 const p=input.product;if(p&&(p.image===undefined))p.image='';if(p&&(!core.validImage(p.image)||p.image.length>140000))fail('Invalid product photo. Use a compressed PNG, JPEG or WebP under 100 KB.');if(!p||!uuid(p.id)||!string(p.name)||!string(p.sku,80)||!integer(p.low_stock)||!['price_myr','price_usd'].every(k=>typeof p[k]==='number'&&Number.isFinite(p[k])&&p[k]>=0&&p[k]<=1e9)||typeof p.active!=='boolean')fail('Check product name, SKU, prices and low-stock threshold.');const [old]=await tx`select * from larz.products where id=${p.id}`;if(old?.deleted_at)fail('This product was deleted.',409);if(old&&old.revision!==p.revision)fail('This product changed. Refresh inventory and try again.',409);if(old)await tx`update larz.products set name=${p.name.trim()},sku=${p.sku.trim()},price_myr=${p.price_myr},price_usd=${p.price_usd},low_stock=${p.low_stock},active=${p.active},image=${p.image},revision=revision+1 where id=${p.id}`;else{if(!integer(p.stock))fail('Opening stock must be a whole number.');await tx`insert into larz.products(id,name,sku,price_myr,price_usd,stock,low_stock,active,image) values(${p.id},${p.name.trim()},${p.sku.trim()},${p.price_myr},${p.price_usd},${p.stock},${p.low_stock},${p.active},${p.image})`;if(p.stock)await tx`insert into larz.stock_movements(product_id,delta,reason,actor,operation_id) values(${p.id},${p.stock},'Opening stock',${user.id},${input.operationId})`}
}else if(action==='stock'){
 if(!uuid(input.id)||!Number.isSafeInteger(input.delta)||!input.delta||Math.abs(input.delta)>1e7||!string(input.reason,300))fail('Enter a nonzero whole quantity and an adjustment reason.');const [p]=await tx`select * from larz.products where id=${input.id}`;if(!p||p.deleted_at)fail('Product not found.',404);if(p.stock+input.delta<0||p.stock+input.delta>1e7)fail('Adjustment would produce an invalid stock quantity.');await tx`update larz.products set stock=stock+${input.delta},revision=revision+1 where id=${p.id}`;await tx`insert into larz.stock_movements(product_id,delta,reason,actor,operation_id) values(${p.id},${input.delta},${input.reason},${user.id},${input.operationId})`;
}else if(action==='settings'){
 if(!core.validBusiness(input.business))fail('Invalid business details.');const [old]=await tx`select * from larz.settings where id=1`;if(old&&old.revision!==input.revision)fail('Business settings changed. Reload before saving.',409);await tx`insert into larz.settings(id,data) values(1,${tx.json(input.business)}) on conflict(id) do update set data=excluded.data,revision=larz.settings.revision+1`;
 }else if(action==='legacy'){
 const d=input.document;if(!d||!uuid(d.id)||!core.validBackup({version:1,business:d.business,documents:[d],draft:null})||core.validate(d).length)fail('Invalid historical document.');const [old]=await tx`select id from larz.documents where id=${d.id}`;if(old)fail('Document is already uploaded.',409);const saved={...d,status:'legacy',revision:1,sourceInvoice:null};await tx`insert into larz.documents(id,number,status,data,created_by) values(${d.id},${d.number},'legacy',${tx.json(saved)},${user.id})`;result={document:saved};
}else if(['document','confirm','cancel'].includes(action)){
 const d=input.document;if(!d||!uuid(d.id)||!core.validBackup({version:1,business:d.business,documents:[],draft:d}))fail('Invalid document fields.');const errors=core.validate(d);if(errors.length)fail(errors[0]);if(!d.business.name.trim())fail('Enter your business name.');const [old]=await tx`select * from larz.documents where id=${d.id}`;if(old?.deleted_at)fail('This document was deleted.',409);if(old&&old.revision!==d.revision)fail('This document changed. Reopen its latest version.',409);if(old&&['cancelled','legacy'].includes(old.status))fail('This document is read-only. Duplicate it to create a new sale.');if(action==='cancel'&&!old)fail('Save the document first.');
 let source=null;if(d.sourceInvoice){if(!uuid(d.sourceInvoice)||d.type!=='receipt')fail('Invalid invoice link.');const [linked]=await tx`select * from larz.documents where id=${d.sourceInvoice}`;if(!linked||linked.deleted_at||linked.status!=='confirmed'||linked.data.type!=='invoice')fail('A receipt must link to a confirmed invoice.');source=linked.id;if(!sameItems(d.items,linked.data.items)||d.currency!==linked.data.currency)fail('Receipt items must match the source invoice.');}
 if(old&&(old.data.type!==d.type||old.source_invoice!==source))fail('Document type and invoice link cannot be changed.');
 if(action==='cancel'){const [linked]=await tx`select id from larz.documents where source_invoice=${d.id} and status<>'cancelled' and deleted_at is null limit 1`;if(linked)fail('Cancel linked receipts before cancelling this invoice.');}
 if(old?.status==='confirmed'&&action!=='cancel'){const [receipt]=await tx`select id from larz.documents where source_invoice=${d.id} and status<>'cancelled' limit 1`;if(receipt&&!sameItems(old.data.items,d.items))fail('Cancel linked receipts before changing invoice items.');}
 const status=action==='cancel'?'cancelled':action==='confirm'?'confirmed':old?.status||'draft';const before=new Map(),after=new Map();const aggregate=(items,map)=>{for(const i of items){if(!uuid(i.productId)||!Number.isSafeInteger(i.qty)||i.qty<1||i.qty>1e7)fail('Select an inventory product and enter a positive whole quantity for each item.');map.set(i.productId,(map.get(i.productId)||0)+i.qty)}};
 if(old?.status==='confirmed'&&!old.source_invoice)aggregate(old.data.items,before);if(status==='confirmed'&&!source)aggregate(d.items,after);
 for(const id of [...new Set([...before.keys(),...after.keys()])].sort()){const [p]=await tx`select * from larz.products where id=${id} for update`;if(!p)fail('Inventory product no longer exists.');const delta=(before.get(id)||0)-(after.get(id)||0);if(delta<0&&(!p.active||p.deleted_at))fail('An item is archived.');if(p.stock+delta<0)fail('Insufficient stock for '+p.name+'. Available: '+p.stock);if(p.stock+delta>1e7)fail('Stock limit exceeded.');if(delta){await tx`update larz.products set stock=stock+${delta},revision=revision+1 where id=${id}`;/* movement inserted after the document below */}}
 let number=old?.number;if(!number){const prefix=(d.type==='receipt'?'REC':'INV')+'-'+new Date().getUTCFullYear();const [n]=await tx`insert into larz.counters(prefix,value) values(${prefix},1) on conflict(prefix) do update set value=larz.counters.value+1 returning value`;number=prefix+'-'+String(n.value).padStart(4,'0')}
 const saved={...d,number,status,sourceInvoice:source,revision:old?old.revision+1:1};await tx`insert into larz.documents(id,number,status,data,revision,source_invoice,created_by) values(${d.id},${number},${status},${tx.json(saved)},${saved.revision},${source},${user.id}) on conflict(id) do update set status=excluded.status,data=excluded.data,revision=excluded.revision,updated_at=now()`;
 for(const id of [...new Set([...before.keys(),...after.keys()])]){const delta=(before.get(id)||0)-(after.get(id)||0);if(delta)await tx`insert into larz.stock_movements(product_id,document_id,delta,reason,actor,operation_id) values(${id},${d.id},${delta},${action==='cancel'?'Sale cancelled':old?.status==='confirmed'?'Sale adjusted':'Sale confirmed'},${user.id},${input.operationId})`}result={document:saved};
}else fail('Unknown operation.',404);
await tx`insert into larz.operations(id,actor,action,payload_hash,result) values(${input.operationId},${user.id},${action},${hash},${tx.json(result)})`;return result})}
module.exports={state,mutate,uuid};
