'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='larz-studio-v1';let storageOK=true;const empty={version:1,business:{name:'',address:'',email:'',phone:'',registration:'',payment:'',terms:'',currency:'MYR',logo:''},documents:[],draft:null};let db;
try{db=JSON.parse(localStorage.getItem(KEY))||structuredClone(empty);if(!validBackup(db))throw Error('Invalid stored data')}catch{db=structuredClone(empty);storageOK=false}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function number(type){const prefix=`${type==='invoice'?'INV':'REC'}-${new Date().getFullYear()}-`;const max=db.documents.filter(d=>d.number.startsWith(prefix)).reduce((m,d)=>Math.max(m,Number(d.number.slice(prefix.length))||0),0);return prefix+String(max+1).padStart(3,'0')}
function fresh(type='invoice'){return {id:crypto.randomUUID(),type,number:number(type),date:today(),due:'',currency:db.business.currency,customer:'',address:'',email:'',reference:'',items:[{description:'',qty:1,price:0}],discount:0,discountType:'fixed',tax:0,shipping:0,paid:0,paymentDate:today(),method:'Bank transfer',paymentReference:'',notes:'',terms:db.business.terms,payment:db.business.payment,business:structuredClone(db.business)}}
let doc=db.draft||fresh();
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500)}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(db));$('#save-status').textContent='Draft saved locally';storageOK=true;return true}catch{$('#save-status').textContent='Not saved — export a backup';if(storageOK)toast('Browser storage is unavailable or full. Export a backup to preserve your work.');storageOK=false;return false}}
function draft(){db.draft=doc;persist();preview()}
function field(label,key,type='text',value=doc[key],extra=''){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" name="${key}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function area(label,key,value=doc[key]){return `<div class="field"><label for="${key}">${label}</label><textarea id="${key}" name="${key}">${esc(value)}</textarea></div>`}
function render(){const b=doc.business;$('#invoice-mode').classList.toggle('active',doc.type==='invoice');$('#receipt-mode').classList.toggle('active',doc.type==='receipt');$('#document-form').innerHTML=`
<div class="form-section"><h2 class="section-title">01 · Your business </h2><div class="business-summary"><div><strong>${esc(b.name||'Add your business details')}</strong><br>${esc(b.email||'')}</div><button type="button" data-action="settings">Edit ↗</button></div></div>
<div class="form-section"><h2 class="section-title">02 · Document details</h2><div class="grid">${field('Document number','number')}${field('Issue date','date','date')}<div class="field"><label for="currency">Currency</label><select id="currency" name="currency"><option value="MYR" ${doc.currency==='MYR'?'selected':''}>RM · Malaysian ringgit</option><option value="USD" ${doc.currency==='USD'?'selected':''}>US$ · US dollar</option></select></div>${doc.type==='invoice'?field('Due date (optional)','due','date'):field('Payment date','paymentDate','date')}</div>${doc.type==='invoice'?'<div class="quick"><button type="button" data-days="0">Due today</button><button type="button" data-days="7">+7 days</button><button type="button" data-days="14">+14 days</button><button type="button" data-days="30">+30 days</button></div>':''}${field('Reference / PO number (optional)','reference')}</div>
<div class="form-section"><h2 class="section-title">03 · Bill to </h2>${field('Customer / company name','customer','text',doc.customer,'list="customers" autocomplete="off"')}<datalist id="customers">${[...new Set(db.documents.map(d=>d.customer))].map(c=>`<option value="${esc(c)}">`).join('')}</datalist><details ${doc.address||doc.email?'open':''}><summary>Address and email</summary>${area('Customer address','address')}${field('Customer email','email','email')}</details></div>
<div class="form-section"><h2 class="section-title">04 · Items <span>Prices in ${doc.currency}</span></h2><div class="item-row item-head"><span>Description</span><span>Qty</span><span>Unit price</span><span></span></div><div id="items">${doc.items.map((i,n)=>`<div class="item-row"><input aria-label="Item ${n+1} description" data-index="${n}" data-key="description" value="${esc(i.description)}" placeholder="Product or service" list="products"><input aria-label="Item ${n+1} quantity" data-index="${n}" data-key="qty" type="number" min="0.001" step="any" value="${i.qty}"><input aria-label="Item ${n+1} unit price" data-index="${n}" data-key="price" type="number" min="0" step="0.01" value="${i.price}"><button type="button" data-remove="${n}" aria-label="Remove item ${n+1}">×</button></div>`).join('')}</div><datalist id="products">${[...new Set(db.documents.flatMap(d=>d.items.map(i=>i.description)))].map(v=>`<option value="${esc(v)}">`).join('')}</datalist><button type="button" class="add-item" data-action="add">＋ Add line item</button></div>
<div class="form-section"><details ${doc.discount||doc.tax||doc.shipping?'open':''}><summary>Discount, tax & additional charge</summary><div class="grid">${field('Discount','discount','number',doc.discount,'min="0" step="0.01"')}<div class="field"><label for="discountType">Discount type</label><select name="discountType" id="discountType"><option value="fixed" ${doc.discountType==='fixed'?'selected':''}>Fixed amount</option><option value="percent" ${doc.discountType==='percent'?'selected':''}>Percentage (%)</option></select></div>${field('Tax (%)','tax','number',doc.tax,'min="0" step="0.01"')}${field('Additional charge','shipping','number',doc.shipping,'min="0" step="0.01"')}</div></details></div>
<div class="form-section"><h2 class="section-title">05 · Payment & notes</h2>${field(doc.type==='receipt'?'Amount received':'Amount already paid','paid','number',doc.paid,'min="0" step="0.01"')}${doc.type==='receipt'?`${field('Payment method','method')}${field('Transaction reference (optional)','paymentReference')}`:area('Payment instructions','payment')}<details ${doc.notes?'open':''}><summary>Notes</summary>${area('Notes','notes')}</details></div>`;preview()}
const money=n=>`${doc.currency==='MYR'?'RM':'US$'} ${(n/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function preview(){const t=InvoiceCore.totals(doc),b=doc.business;$('#preview').innerHTML=`<div class="paper-top"><div>${b.logo?`<img class="logo" src="${esc(b.logo)}" alt="Business logo">`:''}<h3>${esc(b.name||'Your business name')}</h3><div class="address muted">${esc(b.address)}</div><div class="muted">${esc(b.email)}</div></div><div class="meta"><h2>${doc.type.toUpperCase()}</h2><div class="muted">${esc(doc.number)}</div>${doc.type==='receipt'?`<div class="status-pill">${t.balance===0?'PAID IN FULL':t.balance<0?'OVERPAYMENT':'PAYMENT RECEIVED'}</div>`:''}</div><div class="muted business-phone">${esc(b.phone)}</div><div class="meta issue-date"><span class="muted">Issue date </span> ${esc(doc.date)}</div>${b.registration?`<div class="muted business-registration">Reg. ${esc(b.registration)}</div>`:''}</div><div class="bill-row"><div><div class="caption">${doc.type==='receipt'?'RECEIVED FROM':'BILL TO'}</div><strong>${esc(doc.customer||'Customer name')}</strong><div class="address muted">${esc(doc.address)}</div><div class="muted">${esc(doc.email)}</div></div><div class="meta">${doc.type==='invoice'&&doc.due?`<div><span class="muted">Due date </span> ${esc(doc.due)}</div>`:''}${doc.reference?`<div><span class="muted">Reference </span>${esc(doc.reference)}</div>`:''}</div></div><table><thead><tr><th>DESCRIPTION</th><th>QTY</th><th>RATE</th><th>AMOUNT</th></tr></thead><tbody>${doc.items.map(i=>`<tr><td>${esc(i.description||'Product or service')}</td><td>${esc(i.qty)}</td><td>${money(InvoiceCore.round(i.price))}</td><td>${money(InvoiceCore.round(i.qty*i.price))}</td></tr>`).join('')}</tbody></table><div class="totals"><div class="total-row"><span>Subtotal</span><span>${money(t.subtotal)}</span></div>${t.discount?`<div class="total-row"><span>Discount</span><span>−${money(t.discount)}</span></div>`:''}${t.tax?`<div class="total-row"><span>Tax (${esc(doc.tax)}%)</span><span>${money(t.tax)}</span></div>`:''}${Number(doc.shipping)?`<div class="total-row"><span>Additional charge</span><span>${money(InvoiceCore.round(doc.shipping))}</span></div>`:''}<div class="total-row grand"><span>Total</span><span>${money(t.total)}</span></div>${t.paid||doc.type==='receipt'?`<div class="total-row"><span>${doc.type==='receipt'?'Amount received':'Already paid'}</span><span>${money(t.paid)}</span></div>`:''}<div class="total-row"><strong>${t.balance<0?'Credit balance':'Balance due'}</strong><strong>${money(Math.abs(t.balance))}</strong></div></div>${doc.type==='receipt'?`<div class="footer-note"><div class="caption">PAYMENT DETAILS</div>${esc(doc.paymentDate)} · ${esc(doc.method)}${doc.paymentReference?'<br>Reference: '+esc(doc.paymentReference):''}</div>`:doc.payment?`<div class="footer-note"><div class="caption">PAYMENT INSTRUCTIONS</div>${esc(doc.payment)}</div>`:''}${doc.notes||doc.terms?`<div class="footer-note"><div class="caption">NOTES & TERMS</div>${esc([doc.notes,doc.terms].filter(Boolean).join('\n\n'))}</div>`:''}`}
function show(page){document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!==page);document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.page===page));$('#page-title').textContent={editor:'Create a document',history:'Saved documents',settings:'Business settings'}[page];if(page==='history')history();if(page==='settings')settings()}
function save(){if(!doc.business.name.trim()){toast('Add your business name in Business settings first.');return false}const errors=InvoiceCore.validate(doc);if(errors.length){toast(errors[0]);return false}if(db.documents.some(d=>d.id!==doc.id&&d.number===doc.number)){toast('This document number is already saved. Choose a unique number.');return false}const i=db.documents.findIndex(d=>d.id===doc.id);const copy=structuredClone(doc);copy.updatedAt=new Date().toISOString();if(i<0)db.documents.push(copy);else db.documents[i]=copy;db.draft=doc;return persist()}
function history(){const q=$('#search').value.toLowerCase();const rows=db.documents.filter(d=>(d.customer+' '+d.number).toLowerCase().includes(q)).slice().reverse();$('#history-list').innerHTML=rows.length?rows.map(d=>`<div class="saved-row"><div><strong>${esc(d.number)} · ${esc(d.customer)}</strong><small>${esc(d.date)} · ${d.type==='invoice'?'Invoice':'Receipt'} · ${d.currency} ${(InvoiceCore.totals(d).total/100).toFixed(2)}</small></div><div class="saved-actions"><button data-open="${d.id}">Open</button><button data-copy="${d.id}">Duplicate</button>${d.type==='invoice'?`<button data-receipt="${d.id}">Create receipt</button>`:''}<button data-delete="${d.id}">Delete</button></div></div>`).join(''):'<div class="empty">No documents yet. Your saved invoices and receipts will appear here.</div>'}
function settings(){const b=db.business;$('#settings-form').innerHTML=`<h2 class="section-title">Your business details</h2><p><small>These defaults fill new documents. Saving also updates the current draft.</small></p><div class="grid">${field('Business name','name','text',b.name)}${field('Registration number (optional)','registration','text',b.registration)}<div class="full">${area('Business address','address',b.address)}</div>${field('Email','email','email',b.email)}${field('Phone','phone','text',b.phone)}</div><div class="field"><label for="logo">Business logo (PNG, JPEG, or WebP · up to 1 MB)</label><input id="logo" type="file" accept="image/png,image/jpeg,image/webp">${b.logo?`<img src="${esc(b.logo)}" alt="Current logo"><button type="button" id="remove-logo">Remove logo</button>`:''}</div><div class="field"><label for="default-currency">Default currency</label><select name="currency" id="default-currency"><option value="MYR" ${b.currency==='MYR'?'selected':''}>RM · MYR</option><option value="USD" ${b.currency==='USD'?'selected':''}>US$ · USD</option></select></div>${area('Default payment instructions','payment',b.payment)}<button class="primary" type="submit">Save business settings</button>`}
$('#document-form').addEventListener('input',e=>{const el=e.target;if(el.dataset.index!==undefined){doc.items[+el.dataset.index][el.dataset.key]=el.dataset.key==='description'?el.value:Number(el.value)}else if(el.name){if(el.name==='currency'&&el.value!==doc.currency)toast('Currency changed. Prices are not converted; review your amounts.');doc[el.name]=el.type==='number'?Number(el.value):el.value}draft()});
$('#document-form').addEventListener('change',e=>{if(e.target.name==='customer'){const c=db.documents.slice().reverse().find(d=>d.customer===doc.customer);if(c){doc.address=c.address;doc.email=c.email;render();draft()}}if(e.target.dataset.key==='description'){const i=doc.items[+e.target.dataset.index];const found=db.documents.filter(d=>d.currency===doc.currency).flatMap(d=>d.items).reverse().find(x=>x.description===i.description);if(found){i.price=found.price;render();draft()}}});
$('#document-form').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='settings')show('settings');if(b.dataset.action==='add'){doc.items.push({description:'',qty:1,price:0});render();draft()}if(b.dataset.remove!==undefined){if(doc.items.length===1)return toast('Keep at least one item.');doc.items.splice(+b.dataset.remove,1);render();draft()}if(b.dataset.days!==undefined){const date=new Date((doc.date||today())+'T12:00:00');date.setDate(date.getDate()+Number(b.dataset.days));doc.due=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;render();draft()}});
$('#document-form').onsubmit=e=>e.preventDefault();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
function mode(type){if(doc.type===type)return;doc.type=type;doc.id=crypto.randomUUID();doc.number=number(type);render();draft()}
$('#invoice-mode').onclick=()=>mode('invoice');$('#receipt-mode').onclick=()=>mode('receipt');$('#save-doc').onclick=()=>{if(save())toast('Document saved on this device.')};$('#new-doc').onclick=()=>{if(!confirm('Start a new document? Save this document first if you want to keep it.'))return;doc=fresh();render();draft();show('editor')};
$('#print').onclick=()=>{if(!save())return;const old=document.title;document.title=`${doc.number}_${doc.customer}`;window.print();document.title=old};$('#search').oninput=history;
$('#history-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const key=Object.keys(b.dataset)[0],id=b.dataset[key],original=db.documents.find(d=>d.id===id);if(!original)return;if(key==='delete'){if(confirm(`Delete ${original.number} from this browser?`)){db.documents=db.documents.filter(d=>d.id!==id);persist();history()}return}if(!confirm('Open this document? Any unsaved changes to the current draft will be replaced.'))return;doc=structuredClone(original);if(key==='copy'){doc.id=crypto.randomUUID();doc.number=number(doc.type);doc.date=today();doc.due='';doc.paymentDate=today();doc.paid=0;doc.paymentReference=''}if(key==='receipt'){doc.id=crypto.randomUUID();doc.type='receipt';doc.number=number('receipt');doc.reference=original.number;doc.date=today();doc.paymentDate=today();doc.paid=0;doc.paymentReference='';toast('Enter the payment amount and date to confirm the receipt.')}render();draft();show('editor')};
$('#settings-form').onsubmit=async e=>{e.preventDefault();const form=e.target;const data=Object.fromEntries(new FormData(form));const file=$('#logo').files[0];if(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024)return toast('Choose a PNG, JPEG, or WebP image smaller than 1 MB.');data.logo=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}else data.logo=db.business.logo;db.business={...db.business,...data};doc.business=structuredClone(db.business);doc.payment=db.business.payment;doc.terms=db.business.terms;db.draft=doc;if(persist())toast('Business settings saved.');render();settings()};$('#settings-form').onclick=e=>{if(e.target.id==='remove-logo'){db.business.logo='';doc.business.logo='';draft();settings()}};
$('#export').onclick=()=>{db.draft=doc;const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`larz-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function validBackup(v){const str=x=>typeof x==='string';const business=b=>b&&['name','address','email','phone','registration','payment','terms','logo'].every(k=>str(b[k]))&&['MYR','USD'].includes(b.currency)&&(!b.logo||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(b.logo));const document=d=>d&&['invoice','receipt'].includes(d.type)&&['MYR','USD'].includes(d.currency)&&['id','number','date','due','customer','address','email','reference','paymentDate','method','paymentReference','notes','terms','payment'].every(k=>str(d[k]))&&['fixed','percent'].includes(d.discountType)&&business(d.business)&&Array.isArray(d.items)&&d.items.length>0&&d.items.every(i=>i&&str(i.description)&&Number.isFinite(i.qty)&&Number.isFinite(i.price))&&['discount','tax','shipping','paid'].every(k=>Number.isFinite(d[k]));return v&&v.version===1&&business(v.business)&&Array.isArray(v.documents)&&v.documents.every(document)&&(!v.draft||document(v.draft))&&new Set(v.documents.map(d=>d.id)).size===v.documents.length}
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error();const data=JSON.parse(await file.text());if(!validBackup(data))throw Error();if(!confirm('Replace local settings and documents with this backup? Export your current data first if needed.'))return;db=data;doc=db.draft||fresh();persist();render();show('editor');toast('Backup imported.')}catch{toast('This is not a valid Larz backup. Your existing data was kept.')}finally{e.target.value=''}};
render();if(!storageOK)toast('Local storage could not be read. Export backups to preserve your work.');







