let cloud={products:[],documents:[],movements:[],settings:null},cloudReady=false;
const localDocuments=structuredClone(db.documents);
async function api(route,data){const r=await fetch('/api/'+route,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':$('meta[name="csrf-token"]').content}:{},body:data?JSON.stringify(data):undefined});const value=await r.json();if(!r.ok)throw Error(value.error||'Request failed.');return value}
async function refreshCloud(){cloud=await api('state');cloudReady=true;db.documents=[...cloud.documents,...localDocuments.filter(d=>!cloud.documents.some(c=>c.id===d.id)).map(d=>({...d,status:'local'}))];if(cloud.settings)db.business=cloud.settings.data;inventoryView();return cloud}
async function operation(action,payload){return api(action,{...payload,operationId:crypto.randomUUID()})}
const originalRender=render;
render=function(){originalRender();$('#number').readOnly=true;$('#document-form').querySelectorAll('[data-key=qty]').forEach(el=>{el.min='1';el.step='1'});$('#number').title='Assigned centrally when saved';const locked=['cancelled','legacy'].includes(doc.status);$('#document-form').querySelectorAll('input,textarea,select,button').forEach(el=>{if(locked)el.disabled=true});doc.items.forEach((item,n)=>{const input=$(`[data-index="${n}"][data-key="description"]`);if(!input)return;const select=document.createElement('select');select.dataset.productIndex=n;select.setAttribute('aria-label',`Item ${n+1} product`);select.innerHTML='<option value="">Select product…</option>'+cloud.products.filter(p=>p.active||p.id===item.productId).map(p=>`<option value="${esc(p.id)}" ${p.id===item.productId?'selected':''}>${esc(p.name)} · ${esc(p.sku)} (${p.stock} available)</option>`).join('');if(item.description&&!item.productId)select.options[0].textContent=item.description+' — choose product';select.disabled=locked||!!doc.sourceInvoice;input.replaceWith(select)});$('#confirm-sale').hidden=doc.status==='confirmed'||locked||!!doc.sourceInvoice;$('#cancel-sale').hidden=!doc.revision||locked;$('#save-doc').disabled=locked;$('#print').disabled=doc.status==='cancelled';$('#save-status').textContent=doc.status?doc.status[0].toUpperCase()+doc.status.slice(1):'Draft';};
$('#document-form').addEventListener('input',e=>{if(e.target.dataset.productIndex!==undefined)e.stopImmediatePropagation()},true);
$('#document-form').addEventListener('change',e=>{
 if(e.target.name==='currency'){
  if(!doc.sourceInvoice){for(const item of doc.items){const product=cloud.products.find(p=>p.id===item.productId);if(product)item.price=doc.currency==='MYR'?product.price_myr:product.price_usd}}
  render();draft();return;
 }
 const n=e.target.dataset.productIndex;if(n===undefined)return;
 const product=cloud.products.find(p=>p.id===e.target.value);
 doc.items[n]=product?{productId:product.id,description:product.name,qty:Number(doc.items[n].qty)>0?Number(doc.items[n].qty):1,price:doc.currency==='MYR'?product.price_myr:product.price_usd}:{description:'',qty:1,price:0};
 render();draft();
});
save=async function(action='document'){if(doc.status==='legacy')return true;if(doc.status==='cancelled')return false;if(!cloudReady){toast('Connecting to workspace. Try again shortly.');return false}const errors=InvoiceCore.validate(doc);if(errors.length){toast(errors[0]);return false}try{const result=await operation(action,{document:doc});doc=result.document;db.draft=doc;await refreshCloud();persist();render();return true}catch(e){toast(e.message);return false}};
$('#confirm-sale').onclick=async()=>{if(!confirm('Confirm this sale and deduct stock?'))return;const b=$('#confirm-sale');b.disabled=true;try{if(await save('confirm'))toast('Sale confirmed. Stock updated.')}finally{b.disabled=false}};
$('#cancel-sale').onclick=async()=>{if(confirm('Cancel this document? Stock deducted by this sale will be restored.'))if(await save('cancel'))toast('Document cancelled. Stock updated.')};
const baseShow=show;show=function(page){baseShow(page);$('#save-status').hidden=page!=='editor';if(page==='editor')render();if(page==='inventory'){$('#page-title').textContent='Inventory';refreshCloud().catch(e=>toast(e.message))}if(page==='history')refreshCloud().then(history).catch(e=>toast(e.message))};
const baseMode=mode;mode=function(type){if(doc.revision){toast('Use New document to change document type.');return}baseMode(type)};
history=function(){const q=$('#search').value.toLowerCase();const rows=db.documents.filter(d=>(d.customer+' '+d.number).toLowerCase().includes(q)).sort(compareDocumentDates);$('#history-list').innerHTML=rows.length?rows.map(d=>`<div class="saved-row"><div><strong>${esc(d.number)} · ${esc(d.customer)}</strong><small>${esc(d.date)} · ${esc(d.status||'local')} · ${d.currency} ${(InvoiceCore.totals(d).total/100).toFixed(2)}</small></div><div class="saved-actions"><button data-open="${esc(d.id)}">Open</button><button data-copy="${esc(d.id)}">Duplicate</button>${d.type==='invoice'&&d.status==='confirmed'?`<button data-receipt="${esc(d.id)}">Create receipt</button>`:''}${d.status==='local'?`<button data-migrate="${esc(d.id)}">Upload historical record</button>`:''}</div></div>`).join(''):'<div class="empty">No saved documents yet.</div>'};
$('#history-list').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const key=Object.keys(b.dataset)[0],original=db.documents.find(d=>d.id===b.dataset[key]);if(!original)return;if(key==='migrate'){try{await operation('legacy',{document:original});await refreshCloud();history();toast('Historical record uploaded without changing stock.')}catch(err){toast(err.message)}return}if(!confirm('Open this document? Unsaved draft changes will be replaced.'))return;doc=structuredClone(original);if(key==='copy'||key==='receipt'){doc.id=crypto.randomUUID();delete doc.revision;delete doc.status;delete doc.sourceInvoice;doc.date=today();doc.due='';doc.paid=0;doc.paymentDate=today();doc.paymentReference='';if(key==='receipt'){doc.type='receipt';doc.sourceInvoice=original.id;doc.reference=original.number;toast('Enter the amount received. This receipt will not deduct stock again.')}doc.number=number(doc.type)}render();draft();show('editor')};
const baseSettingsSubmit=$('#settings-form').onsubmit;$('#settings-form').onsubmit=async e=>{e.preventDefault();if(!cloudReady)return toast('Workspace is not connected.');await baseSettingsSubmit(e);try{await operation('settings',{business:db.business,revision:cloud.settings?.revision||0});await refreshCloud();toast('Business settings saved to workspace.')}catch(err){toast(err.message)}};
$('#settings-form').addEventListener('click',async e=>{if(e.target.id==='remove-logo')try{await operation('settings',{business:db.business,revision:cloud.settings?.revision||0});await refreshCloud()}catch(err){toast(err.message)}});
function inventoryView(){const q=($('#product-search').value||'').toLowerCase();$('#inventory-list').innerHTML=cloud.products.filter(p=>(p.name+' '+p.sku).toLowerCase().includes(q)).map(p=>`<div class="saved-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.sku)} · RM ${p.price_myr.toFixed(2)} / US$ ${p.price_usd.toFixed(2)}${p.active?'':' · Archived'}</small><span class="stock-count ${p.stock<=p.low_stock?'low-stock':''}">${p.stock} in stock${p.stock<=p.low_stock?' · Low stock':''}</span></div><div class="saved-actions"><button data-edit-product="${p.id}">Edit</button><button data-stock="${p.id}">Adjust stock</button></div></div>`).join('')||'<div class="empty">Add your first product to start tracking inventory.</div>';$('#movement-list').innerHTML=cloud.movements.map(m=>`<div class="movement-row"><strong>${esc(m.name)}</strong><span>${m.delta>0?'+':''}${m.delta}</span><span>${esc(m.reason)}${m.number?' · '+esc(m.number):''}</span><small>${esc(new Date(m.created_at).toLocaleString())}</small></div>`).join('')||'<p>No stock movements yet.</p>'}
function editProduct(p){p=p||{id:crypto.randomUUID(),name:'',sku:'',price_myr:0,price_usd:0,stock:0,low_stock:5,active:true};const form=$('#product-form');form.hidden=false;form.innerHTML=`<h2>${p.revision?'Edit product':'Add product'}</h2><div class="grid">${[['Name','name','text'],['SKU','sku','text'],['Price RM','price_myr','number'],['Price US$','price_usd','number'],[p.revision?'Current stock (use Adjust stock)':'Opening stock','stock','number'],['Low-stock threshold','low_stock','number']].map(([label,key,type])=>`<div class="field"><label for="product-${key}">${label}</label><input id="product-${key}" name="${key}" type="${type}" value="${esc(p[key])}" required maxlength="${key==='sku'?80:200}" ${type==='number'?'min="0" max="10000000" step="'+(key.startsWith('price')?'0.01':'1')+'"':''} ${key==='stock'&&p.revision?'readonly':''}></div>`).join('')}</div><label><input type="checkbox" name="active" ${p.active?'checked':''}> Available for new sales</label><button class="primary">Save product</button><button type="button" id="close-product">Cancel</button>`;$('#close-product').onclick=()=>form.hidden=true;form.onsubmit=async e=>{e.preventDefault();const fields=new FormData(form),product={...p};for(const k of ['name','sku'])product[k]=fields.get(k);for(const k of ['price_myr','price_usd','stock','low_stock'])product[k]=Number(fields.get(k));product.active=fields.has('active');const b=form.querySelector('button');b.disabled=true;try{await operation('product',{product});await refreshCloud();form.hidden=true;toast('Product saved.')}catch(err){toast(err.message)}finally{b.disabled=false}}}
$('#add-product').onclick=()=>editProduct();$('#refresh-stock').onclick=()=>refreshCloud().catch(e=>toast(e.message));$('#product-search').oninput=inventoryView;
$('#inventory-list').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.editProduct||b.dataset.stock,p=cloud.products.find(p=>p.id===id);if(!p)return;if(b.dataset.editProduct)return editProduct(p);const amount=prompt('Stock adjustment for '+p.name+'. Enter a positive quantity to restock, or a negative quantity to remove units.');if(amount===null)return;const reason=prompt('Reason for this adjustment:','Restock');if(reason===null)return;try{await operation('stock',{id,delta:Number(amount),reason});await refreshCloud();toast('Stock updated.')}catch(err){toast(err.message)}};
// Keep imported historical files local until explicitly uploaded; never infer stock deductions.
const baseImport=$('#import').onchange;$('#import').onchange=async e=>{await baseImport(e);for(const d of db.documents)if(!localDocuments.some(x=>x.id===d.id)&&!cloud.documents.some(x=>x.id===d.id))localDocuments.push(d);if(cloudReady){await refreshCloud();render()}};
refreshCloud().then(()=>{if(!doc.business.name&&cloud.settings){doc.business=structuredClone(db.business);doc.payment=db.business.payment}render();toast('Shared workspace connected.');}).catch(e=>toast(e.message));
