(function(root){
 const round=n=>Math.round((Number(n)+Number.EPSILON)*100);
 function totals(d){const subtotal=d.items.reduce((s,i)=>s+round(Number(i.qty)*Number(i.price)),0);const discount=Math.min(subtotal,d.discountType==='percent'?Math.round(subtotal*Number(d.discount||0)/100):round(d.discount||0));const tax=Math.round((subtotal-discount)*Number(d.tax||0)/100);const total=subtotal-discount+tax+round(d.shipping||0)+round(d.shippingCost||0);const paid=round(d.paid||0);return {subtotal,discount,tax,total,paid,balance:total-paid};}
 function validate(d){const errors=[];if(!d.number.trim())errors.push('Enter a document number.');if(!d.customer.trim())errors.push('Enter a customer name.');if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date))errors.push('Choose an issue date.');if(!d.items.length||d.items.some(i=>!i.description.trim()||!Number.isFinite(Number(i.qty))||Number(i.qty)<=0||!Number.isFinite(Number(i.price))||Number(i.price)<0))errors.push('Each item needs a description, a quantity above zero, and a nonnegative price.');for(const key of ['discount','tax','shipping','paid'])if(!Number.isFinite(Number(d[key]))||Number(d[key])<0)errors.push('Adjustments and payments must be nonnegative numbers.');if(d.discountType==='percent'&&Number(d.discount)>100)errors.push('Percentage discount cannot exceed 100%.');if(d.type==='receipt'&&(!d.paymentDate||Number(d.paid)<=0))errors.push('A receipt needs a payment date and an amount received above zero.');return errors;}
 const api={round,totals,validate};root.InvoiceCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
(function(root){
 const api=root.InvoiceCore,oldValidate=api.validate;
 const text=(v,max=5000)=>typeof v==='string'&&v.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v);
 const num=(v,max=1e9)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max;
 const date=v=>text(v,10)&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
 const email=v=>text(v,254)&&(!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v));
 function logo(v){if(v==='')return true;if(!text(v,1400000))return false;const m=/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(v);if(!m)return false;try{const bytes=typeof atob==='function'?atob(m[2]):Buffer.from(m[2],'base64').toString('binary');return bytes.length<=1048576&&((m[1]==='png'&&bytes.startsWith('\x89PNG\r\n\x1a\n'))||(m[1]==='jpeg'&&bytes.startsWith('\xff\xd8\xff'))||(m[1]==='webp'&&bytes.startsWith('RIFF')&&bytes.slice(8,12)==='WEBP'))}catch{return false}}
 function business(b){return !!b&&['name','address','phone','registration','payment','terms'].every(k=>text(b[k]))&&email(b.email)&&['MYR','USD'].includes(b.currency)&&logo(b.logo)}
 function shape(d){return !!d&&['invoice','receipt'].includes(d.type)&&['MYR','USD'].includes(d.currency)&&text(d.id,64)&&/^[a-zA-Z0-9_-]+$/.test(d.id)&&['number','customer','address','reference','method','paymentReference','notes','terms','payment'].every(k=>text(d[k]))&&email(d.email)&&['date','due','paymentDate'].every(k=>d[k]===''||date(d[k]))&&['fixed','percent'].includes(d.discountType)&&business(d.business)&&Array.isArray(d.items)&&d.items.length>0&&d.items.length<=200&&d.items.every(i=>i&&text(i.description,2000)&&num(i.qty,1e6)&&num(i.price,1e9))&&['discount','tax','shipping','paid'].every(k=>num(d[k]))&&(d.shippingCost===undefined||num(d.shippingCost))&&d.tax<=100&&(d.discountType!=='percent'||d.discount<=100)&&Object.values(api.totals(d)).every(Number.isSafeInteger)}
 api.validBusiness=business;api.validImage=logo;
 api.validBackup=v=>!!v&&v.version===1&&business(v.business)&&Array.isArray(v.documents)&&v.documents.length<=2000&&v.documents.every(shape)&&(!v.draft||shape(v.draft))&&new Set(v.documents.map(d=>d.id)).size===v.documents.length;
 api.validate=d=>{if(!d||typeof d!=='object')return ['Invalid document.'];if(!text(d.number)||!text(d.customer)||!Array.isArray(d.items)||d.items.length>200||!d.items.every(i=>i&&text(i.description,2000)&&num(i.qty,1e6)&&num(i.price)))return ['Check text lengths and item amounts (maximum 200 items).'];if(!date(d.date)||d.due&&!date(d.due)||d.type==='receipt'&&!date(d.paymentDate))return ['Enter valid calendar dates.'];if(d.email!==undefined&&!email(d.email))return ['Enter a valid customer email.'];if(d.currency!==undefined&&!['MYR','USD'].includes(d.currency)||!['invoice','receipt'].includes(d.type)||!['fixed','percent'].includes(d.discountType))return ['Invalid document options.'];if(['discount','tax','shipping','paid'].some(k=>!num(d[k]))||(d.shippingCost!==undefined&&!num(d.shippingCost))||d.tax>100)return ['Enter valid amounts; tax must be between 0 and 100%.'];if(['address','reference','method','paymentReference','notes','terms','payment'].some(k=>d[k]!==undefined&&!text(d[k])))return ['Text fields must be no longer than 5,000 characters.'];if(d.business&&!business(d.business))return ['Check business details and logo.'];if(!Object.values(api.totals(d)).every(Number.isSafeInteger))return ['Document total is too large.'];return oldValidate(d)};
})(typeof window!=='undefined'?window:globalThis);
